# Auto-generated by scripts/gen_stubs.py from ai4sweng/metrics.json.
# Do not edit by hand -- edit metrics.json and re-run the generator instead:
#     python scripts/gen_stubs.py
# This file only affects static type checkers / IDE autocomplete; it has no
# effect on runtime behavior.

from ai4sweng.kpi import KPIMetric as KPIMetric
from ai4sweng.kpi import _BoundKPIMetric as _BoundKPIMetric
from ai4sweng.kpi import OTelSpec as OTelSpec

class _KIO1Namespace:
    developer_productivity: _BoundKPIMetric

class _KIO2Namespace:
    code_generation_speed: _BoundKPIMetric
    issue_resolution_speed: _BoundKPIMetric
    bug_fix_time: _BoundKPIMetric
    customer_reported_issues: _BoundKPIMetric

class _KIO3Namespace:
    code_generation_speed: _BoundKPIMetric
    issue_resolution_speed: _BoundKPIMetric

class _KIO4Namespace:
    code_generation_speed: _BoundKPIMetric
    issue_resolution_speed: _BoundKPIMetric
    code_quality_improvement: _BoundKPIMetric
    review_score_increase: _BoundKPIMetric

class _KIO5Namespace:
    ...

class _KIO6Namespace:
    ...

class _KIO7Namespace:
    code_generation_speed: _BoundKPIMetric
    issue_resolution_speed: _BoundKPIMetric
    lifecycle_energy_reduction: _BoundKPIMetric
    deployment_energy_efficiency: _BoundKPIMetric
    code_quality_improvement: _BoundKPIMetric
    review_score_increase: _BoundKPIMetric
    developer_productivity: _BoundKPIMetric
    time_to_market_pilot_feature_release: _BoundKPIMetric
    bug_fix_time: _BoundKPIMetric
    customer_reported_issues: _BoundKPIMetric
    annual_cost_saving: _BoundKPIMetric
    refactoring_reduction: _BoundKPIMetric
    technical_debt_reduction: _BoundKPIMetric

class _KIO8Namespace:
    lifecycle_energy_reduction: _BoundKPIMetric
    deployment_energy_efficiency: _BoundKPIMetric
    annual_cost_saving: _BoundKPIMetric
    cross_architecture_build_success_rate: _BoundKPIMetric

class _KIO9Namespace:
    code_quality_improvement: _BoundKPIMetric
    review_score_increase: _BoundKPIMetric
    refactoring_reduction: _BoundKPIMetric
    technical_debt_reduction: _BoundKPIMetric

class _KIO10Namespace:
    lifecycle_energy_reduction: _BoundKPIMetric
    deployment_energy_efficiency: _BoundKPIMetric
    annual_cost_saving: _BoundKPIMetric

class _KIO11Namespace:
    time_to_market_pilot_feature_release: _BoundKPIMetric
    bug_fix_time: _BoundKPIMetric
    customer_reported_issues: _BoundKPIMetric

class _KIO12Namespace:
    ...

class _KIO13Namespace:
    developer_productivity: _BoundKPIMetric
    adoption_rate: _BoundKPIMetric
    active_usage_satisfaction: _BoundKPIMetric

class _KPIInterface:
    KIO1: _KIO1Namespace
    KIO2: _KIO2Namespace
    KIO3: _KIO3Namespace
    KIO4: _KIO4Namespace
    KIO5: _KIO5Namespace
    KIO6: _KIO6Namespace
    KIO7: _KIO7Namespace
    KIO8: _KIO8Namespace
    KIO9: _KIO9Namespace
    KIO10: _KIO10Namespace
    KIO11: _KIO11Namespace
    KIO12: _KIO12Namespace
    KIO13: _KIO13Namespace
    def list_kios(self) -> list[str]: ...
    def list_kpis(self) -> list[KPIMetric]: ...
    def get_kio_metrics(self, kio_name: str) -> dict[str, _BoundKPIMetric]: ...
    def get_kpi(self, kpi_id: str) -> KPIMetric: ...
    def reload(self) -> None: ...

KPI: _KPIInterface
