#!/usr/bin/env python
"""Regenerate ai4sweng/__init__.pyi from ai4sweng/metrics.json.

Why this exists: `KPI.KIO7`, `KPI.KIO7.code_generation_speed`, etc. are built
dynamically at runtime from metrics.json (see ai4sweng/kpi.py). Real Python
sees them fine, but static type checkers and editor autocomplete (Pylance,
mypy, PyCharm) only read source code — they never execute _load(), so they
can't discover attributes that only exist at runtime. This script renders
that dynamic shape into a static stub file, ai4sweng/__init__.pyi, which
editors and type checkers pick up automatically (see PEP 561 / ai4sweng/py.typed).

Run this after adding, removing, or renaming a KPI or a KIO in metrics.json:

    python scripts/gen_stubs.py            # regenerate the stub
    python scripts/gen_stubs.py --check    # exit 1 if the stub is stale (used in tests/CI)
"""
import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METRICS_PATH = ROOT / "ai4sweng" / "metrics.json"
STUB_PATH = ROOT / "ai4sweng" / "__init__.pyi"

HEADER = """# Auto-generated by scripts/gen_stubs.py from ai4sweng/metrics.json.
# Do not edit by hand -- edit metrics.json and re-run the generator instead:
#     python scripts/gen_stubs.py
# This file only affects static type checkers / IDE autocomplete; it has no
# effect on runtime behavior.

from ai4sweng.kpi import KPIMetric as KPIMetric
from ai4sweng.kpi import _BoundKPIMetric as _BoundKPIMetric
from ai4sweng.kpi import OTelSpec as OTelSpec
"""


def _slugify(name: str) -> str:
    """Same rule as ai4sweng.kpi._slugify, duplicated to keep this script standalone."""
    ascii_name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", ascii_name).strip("_").lower()
    return slug or "kpi"


def render_stub(metrics_path: Path) -> str:
    """Render the full ai4sweng/__init__.pyi text for the metrics.json at `metrics_path`."""
    raw = json.loads(Path(metrics_path).read_text(encoding="utf-8"))
    kios = raw.get("kios", [])
    kpis = raw.get("kpis", [])

    by_kio = {kio: [] for kio in kios}
    for entry in kpis:
        attr = entry.get("attr") or _slugify(entry["name"])
        for kio in entry.get("kios", []):
            by_kio.setdefault(kio, []).append(attr)

    lines = [HEADER]
    for kio in kios:
        lines.append(f"class _{kio}Namespace:")
        attrs = by_kio.get(kio, [])
        if attrs:
            lines.extend(f"    {attr}: _BoundKPIMetric" for attr in attrs)
        else:
            lines.append("    ...")
        lines.append("")

    lines.append("class _KPIInterface:")
    lines.extend(f"    {kio}: _{kio}Namespace" for kio in kios)
    lines.append("    def list_kios(self) -> list[str]: ...")
    lines.append("    def list_kpis(self) -> list[KPIMetric]: ...")
    lines.append("    def get_kio_metrics(self, kio_name: str) -> dict[str, _BoundKPIMetric]: ...")
    lines.append("    def get_kpi(self, kpi_id: str) -> KPIMetric: ...")
    lines.append("    def reload(self) -> None: ...")
    lines.append("")
    lines.append("KPI: _KPIInterface")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if the stub is stale instead of writing it")
    args = parser.parse_args()

    stub_text = render_stub(METRICS_PATH)

    if args.check:
        current = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.exists() else ""
        if current != stub_text:
            print(f"{STUB_PATH.relative_to(ROOT)} is out of date. Run: python scripts/gen_stubs.py", file=sys.stderr)
            return 1
        print(f"{STUB_PATH.relative_to(ROOT)} is up to date.")
        return 0

    STUB_PATH.write_text(stub_text, encoding="utf-8")
    print(f"Wrote {STUB_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
